# Config for Text variable fonts only
sources:
  - WixMadeforText.designspace
  - WixMadeforText-Italic.designspace
familyName: "Wix Made for Text"
autohintTTF: true
buildVariable: true
buildStatic: false
logLevel: WARNING
outputDir:
  '../fonts/Text'
category:
  - SANS_SERIF
axisOrder:
  - wght
  - ital
stat:
  WixMadeforText[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2
  WixMadeforText-Italic[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
  - name: Italic
    tag: ital
    values:
    - name: Italic
      value: 1