# Config for building Display variable fonts only
sources:
  - WixMadeforDisplay.designspace
familyName: "Wix Made for Display"
logLevel: WARNING
outputDir:
  '../fonts/Display'
#stylespaceFile: "WixMadeforVF.stylespace"
autohintTTF: true
buildStatic: true
#googleFonts:
#  true
category:
  - SANS_SERIF
axisOrder:
  - wght
stat:
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
